package dps_swum;

import java.io.File;
import java.io.IOException;

import dps_swum.swum.SWUMEvaluationPipeline;

/**
 * Entry point for the SWUM-based design pattern summarization application.
 * <p>
 * This application processes JSON files generated by the DPS-NLG pipeline using
 * Software Word Usage Model (SWUM) techniques to generate code summaries. SWUM
 * analyzes identifier names and code structure to produce natural language descriptions.
 * </p>
 * <p>
 * Key responsibilities:
 * <ul>
 *   <li>Verify that required JSON output directory exists</li>
 *   <li>Create SWUM output directories</li>
 *   <li>Initialize and run the SWUM evaluation pipeline</li>
 *   <li>Handle errors and report status</li>
 * </ul>
 * </p>
 * 
 * @author Najam
 */
public class SWUMApplication {

    /**
     * Main entry point for the SWUM summarization application.
     * <p>
     * Checks for required input directories, creates output directories,
     * and runs the complete SWUM processing pipeline.
     * </p>
     * 
     * @param args command line arguments (currently unused)
     * @throws IOException if file I/O operations fail
     */
    public static void main(String[] args) throws IOException {
        System.out.println("Starting SWUM-based Design Pattern Summarizer...");
        
        // Check if JSON output directory exists
        File jsonOutputDir = new File("output/json-output");
        if (!jsonOutputDir.exists()) {
            System.err.println("Error: JSON output directory not found at: " + jsonOutputDir.getAbsolutePath());
            System.err.println("Please run the DPS-NLG project first to generate JSON files.");
            return;
        }
        
        // Create SWUM output directory
        File swumOutputDir = new File("output/swum-output");
        if (!swumOutputDir.exists()) {
            swumOutputDir.mkdirs();
        }
        
        try {
            // Run SWUM evaluation pipeline
            SWUMEvaluationPipeline pipeline = new SWUMEvaluationPipeline();
            pipeline.runCompletePipeline();
            
            System.out.println("\nSWUM processing completed successfully!");
            System.out.println("SWUM summaries available in: " + swumOutputDir.getAbsolutePath());
            
        } catch (Exception e) {
            System.err.println("Error during SWUM processing: " + e.getMessage());
            e.printStackTrace();
        }
    }
}

